[benchmark-framework]
frameworks = [
    'tensorflowquantum',
]


[framework.intel]
    [framework.intel.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.intel.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5

[framework.mindquantum]
    [framework.mindquantum.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 5
        qubit_max = 24

[framework.paddlequantum]
    [framework.paddlequantum.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.paddlequantum.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.paddlequantum.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 5
        qubit_max = 6

[framework.qiskit]
    [framework.qiskit.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.qiskit.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5

[framework.tensorflowquantum]
    [framework.tensorflowquantum.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.tensorflowquantum.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.tensorflowquantum.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 5
        qubit_max = 6