[benchmark-framework]
frameworks = [
    'intel',
]


[framework.intel]
    [framework.intel.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5
    [framework.intel.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 5

[framework.mindquantum]
    [framework.mindquantum.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_4_regular_qaoa]
        platform = ['cpu', 'gpu']
        qubit_min = 5
        qubit_max = 24
