[benchmark-framework]
frameworks = [
    'intel',
    'mindquantum',
    'paddlequantum',
    'qiskit',
    'tensorflowquantum',
    'qulacs',
    'quest',
    'qpanda',
    'tensorcircuit'
]


[framework.intel]
    [framework.intel.benchmark_random_circuit]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 24
    [framework.intel.benchmark_random_ham]
        platform = ['cpu']
        qubit_min = 4
        qubit_max = 24

[framework.mindquantum]
    [framework.mindquantum.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.mindquantum.benchmark_4_regular_qaoa]
        platform = ['cpu', 'gpu']
        qubit_min = 5
        qubit_max = 24

[framework.paddlequantum]
    [framework.paddlequantum.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 20
    [framework.paddlequantum.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 13
    [framework.paddlequantum.benchmark_4_regular_qaoa]
        platform = ['cpu', 'gpu']
        qubit_min = 5
        qubit_max = 20

[framework.qiskit]
    [framework.qiskit.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.qiskit.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24

[framework.tensorflowquantum]
    [framework.tensorflowquantum.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.tensorflowquantum.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.tensorflowquantum.benchmark_4_regular_qaoa]
        platform = ['cpu', 'gpu']
        qubit_min = 5
        qubit_max = 24

[framework.qulacs]
    [framework.qulacs.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.qulacs.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.qulacs.benchmark_4_regular_qaoa]
        platform = ['cpu']
        qubit_min = 5
        qubit_max = 24

[framework.quest]
    [framework.quest.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24
    [framework.quest.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 24

[framework.qpanda]
    [framework.qpanda.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 20
    [framework.qpanda.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 20

[framework.tensorcircuit]
    [framework.tensorcircuit.benchmark_random_circuit]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 17
    [framework.tensorcircuit.benchmark_random_ham]
        platform = ['cpu', 'gpu']
        qubit_min = 4
        qubit_max = 17
    [framework.tensorcircuit.benchmark_4_regular_qaoa]
        platform = ['cpu', 'gpu']
        qubit_min = 5
        qubit_max = 17
